name: "Release"

on:
  workflow_call:

jobs:
  Release:
      # considera que todos os outros testes ja foram rodados antes do release
      if: ${{!contains(github.event.head_commit.message, 'chore(release):')}}
      runs-on: ubuntu-latest
      steps:
        - uses: actions/setup-python@v2
          with:
            python-version: 3.10.4
        - name: Checkout code
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
            token: ${{ secrets.ADMIN_GITHUB_PAT}}
        - name: Semantic Release
          uses: relekang/python-semantic-release@master
          with:
            github_token: ${{ secrets.ADMIN_GITHUB_PAT }}
